- name: Restore machine
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:

  - name: Update host
    dnf: name=* state=latest

  - name: Install essential packages
    dnf: name={{item}} state=latest
    with_items:
      - autokey-gtk
      - meld
      - terminator
      - gnome-tweak-tool
      - gparted
      - telnet
      - httpie
      - oathtool
      - unzip
      - xclip
      - p7zip
      - git
      - alacarte
      - NetworkManager-vpnc
      - NetworkManager-openvpn
      - vpnc
      - openvpn
      - vim
      - gpaste
      - gnome-shell-extension-gpaste
      - libselinux-python
      - java-1.8.0-openjdk-devel
      - firefox
      - kernel-devel
      - ImageMagick
      - expect
      - grive2
      - tilix
      - chrome-gnome-shell
      - system-config-printer
      - adapta-backgrounds.noarch
      - adapta-gtk-theme.noarch

  - name: Install nautilus extensions
    dnf: name={{item}} state=latest
    with_items:
      - nautilus-open-terminal
      - nautilus-extensions
      - nautilus-sendto

  - name: Install KVM
    dnf: name={{item}} state=latest
    with_items:
      - '@virtualization'
      - virt-install
      - virt-viewer
      - libvirt-daemon-config-network

  - name: Add user to docker group
    shell: usermod -aG libvirt pbarbosa

  - name: Enable libvirtd and start it
    service: name=libvirtd enabled=yes state=started

  - name: Disable firewalld
    service: name=firewalld enabled=no state=stopped

  - name: Create apps folder
    file: path=/home/pbarbosa/apps state=directory owner=pbarbosa group=pbarbosa

  - name: Create fonts folder
    file: path=/home/pbarbosa/.fonts/ state=directory owner=pbarbosa group=pbarbosa
    file: path=/home/pbarbosa/.fonts/meslo state=directory owner=pbarbosa group=pbarbosa

  - name: Install fonts
    unarchive: src=fonts.zip dest=/home/pbarbosa/.fonts/meslo owner=pbarbosa

  - name: Install google chrome
    dnf: name=https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm state=present

  - name: Download Atom
    get_url:
      url: https://atom.io/download/rpm
      dest: /tmp/atom.rpm

  - name: Install Atom
    dnf: name=/tmp/atom.rpm state=present

  - name: Install atoms sync-settings plugins
    shell: apm install sync-settings

  - name: Install Dropbox
    dnf: name=https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2015.10.28-1.fedora.x86_64.rpm state=present

  - name: Download telegram
    get_url:
      url: https://telegram.org/dl/desktop/linux
      dest: /tmp/telegram.tar.xz

  - name: Install telegram
    unarchive: src=/tmp/telegram.tar.xz dest=/home/pbarbosa/apps owner=pbarbosa

  - name: Install RPM Fusion
    dnf: name=http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-28.noarch.rpm state=present


  - name: Download flash player
    dnf: name=http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm state=present

  - name: Import flash player repo key
    shell: rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-adobe-linux

  - name: Install flash player
    dnf: name=flash-plugin state=present

  - name: Install Adobe Reader9
    dnf: name=http://ardownload.adobe.com/pub/adobe/reader/unix/9.x/9.5.5/enu/AdbeRdr9.5.5-1_i486linux_enu.rpm state=present

  - name: Configure docker repo
    copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo

  - name: Create group docker
    group: name=docker state=present

  - name: Add user to docker group
    shell: usermod -aG docker pbarbosa

  - name: Install docker
    dnf: name=docker-engine state=latest

  - name: Install docker-compose
    shell: curl -L https://github.com/docker/compose/releases/download/1.8.1/run.sh > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose

  - name: Install CODECS
    dnf: name={{item}} state=latest
    with_items:
      - flac
      - ffmpeg
      - gpac-libs
      - lame
      - libfc14audiodecoder
      - mencoder
      - mplayer
      - x264
      - x265
      - gstreamer-plugins-espeak
      - gstreamer-plugins-fc
      - gstreamer-rtsp
      - gstreamer-plugins-good
      - gstreamer-plugins-bad
      - gstreamer-plugins-bad-free-extras
      - gstreamer-ffmpeg
      - gstreamer1-plugins-base
      - gstreamer1-libav
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-base-tools
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugins-ugly
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-good


  - name: Install WARSAW (Para acesso à bancos como CAIXA, BB, Itaú, BRB)
    dnf: name=https://cloud.gastecnologia.com.br/gas/diagnostico/warsaw_setup_64.rpm state=present
